from typing import Any, List, Tuple, Union, overload

from nv_raylib.vector2.vector2 import Vector2
from nv_raylib.vector4.vector4 import Vector4

class Rect:
    position: Vector2
    size: Vector2

    @staticmethod
    def new(position: Vector2, size: Vector2) -> Rect: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(
        self,
        arg_0: Union[
            Vector2, Rect, Vector4, Tuple[float, float, float, float], List[float]
        ],
    ) -> None: ...
    @overload
    def __init__(
        self,
        arg_0: Union[Vector2, Tuple[float, float], List[float]],
        arg_1: Union[Vector2, Tuple[float, float], List[float]],
    ) -> None: ...
    @overload
    def __init__(self, x: float, y: float, w: float, h: float) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, value: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, value: float) -> None: ...
    @property
    def w(self) -> float: ...
    @w.setter
    def w(self, value: float) -> None: ...
    @property
    def h(self) -> float: ...
    @h.setter
    def h(self, value: float) -> None: ...
    def get_width(self) -> float: ...
    def get_height(self) -> float: ...
    @property
    def width(self) -> float: ...
    @width.setter
    def width(self, value: float) -> None: ...
    @property
    def height(self) -> float: ...
    @height.setter
    def height(self, value: float) -> None: ...
    @property
    def left(self) -> float: ...
    @left.setter
    def left(self, value: float) -> None: ...
    @property
    def top(self) -> float: ...
    @top.setter
    def top(self, value: float) -> None: ...
    @property
    def right(self) -> float: ...
    @right.setter
    def right(self, value: float) -> None: ...
    @property
    def bottom(self) -> float: ...
    @bottom.setter
    def bottom(self, value: float) -> None: ...
    @property
    def centerx(self) -> float: ...
    @centerx.setter
    def centerx(self, value: float) -> None: ...
    @property
    def centery(self) -> float: ...
    @centery.setter
    def centery(self, value: float) -> None: ...
    @property
    def center(self) -> Vector2: ...
    @center.setter
    def center(
        self, value: Union[Vector2, Tuple[float, float], List[float]]
    ) -> None: ...
    def collide_point(
        self, point: Union[Vector2, Tuple[float, float], List[float]]
    ) -> bool: ...
    def collide_point_vector2(self, point: Vector2) -> bool: ...
    def collide_point_tuple(self, point: Tuple[float, float]) -> bool: ...
    def collide_point_list(self, point: List[float]) -> bool: ...
    def collide_rect(
        self,
        other: Union[Rect, Vector4, Tuple[float, float, float, float], List[float]],
    ) -> bool: ...
    def collide_rect_vector4(self, other: Vector4) -> bool: ...
    def collide_rect_rect(self, other: Rect) -> bool: ...
    def collide_rect_tuple(self, other: Tuple[float, float, float, float]) -> bool: ...
    def collide_rect_list(self, other: List[float]) -> bool: ...
    def get_vector4(self) -> Vector4: ...
    def get_tuple(self) -> Tuple[float, float, float, float]: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
