from typing import Any, Sequence, Tuple, Union, overload

class Vector2:
    x: float
    y: float

    @staticmethod
    def from_vector2(other: "Vector2") -> "Vector2": ...
    @staticmethod
    def from_list(other: list) -> "Vector2": ...
    @staticmethod
    def from_tuple(other: tuple) -> "Vector2": ...
    @staticmethod
    def from_ints(x: int, y: int) -> "Vector2": ...
    @staticmethod
    def from_floats(x: float, y: float) -> "Vector2": ...
    @staticmethod
    def from_xy(x: float | int, y: float | int) -> "Vector2": ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, vector: "Vector2") -> None: ...
    @overload
    def __init__(self, sequence: Sequence[float]) -> None: ...
    @overload
    def __init__(self, x: float, y: float) -> None: ...
    @property
    def xx(self) -> "Vector2": ...
    @property
    def yy(self) -> "Vector2": ...
    @property
    def xy(self) -> "Vector2": ...
    @property
    def yx(self) -> "Vector2": ...
    def get_tuple(self) -> Tuple[float, float]: ...
    def get_int_tuple(self) -> Tuple[int, int]: ...
    def get_rounded_tuple(self) -> Tuple[int, int]: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __add__(self, other: "Vector2") -> "Vector2": ...
    def __sub__(self, other: "Vector2") -> "Vector2": ...
    def __mul__(self, other: Union["Vector2", int, float]) -> "Vector2": ...
    def __truediv__(self, other: Union["Vector2", int, float]) -> "Vector2": ...
    def __floordiv__(self, other: Union["Vector2", int, float]) -> "Vector2": ...
    def __iadd__(self, other: "Vector2") -> "Vector2": ...
    def __isub__(self, other: "Vector2") -> "Vector2": ...
    def __imul__(self, other: "Vector2") -> "Vector2": ...
    def __neg__(self) -> "Vector2": ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
    def __copy__(self) -> "Vector2": ...
    def __deepcopy__(self, memo: Any) -> "Vector2": ...
    def copy(self) -> "Vector2": ...
    def to_round(self) -> "Vector2": ...
    def get_round(self) -> "Vector2": ...
    def to_abs(self) -> "Vector2": ...
    def get_abs(self) -> "Vector2": ...
    def to_neg(self) -> "Vector2": ...
    def get_neg(self) -> "Vector2": ...
    @property
    def length(self) -> float: ...
    def sadd(self, new_vec: "Vector2", old_vec: "Vector2") -> None: ...
    def to_normalized(self) -> "Vector2": ...
    def get_normalized(self) -> "Vector2": ...
    def distance_to(self, other: "Vector2") -> float: ...
    def distance_squared_to(self, other: "Vector2") -> float: ...
    def dot(self, other: "Vector2") -> float: ...
