# This file was generated by stubgen-pyx v0.2.16 from src/nv_raylib/draw/draw.pyx

from nv_raylib.color.color import Color
from nv_raylib.vector2.vector2 import Vector2


class draw:
    @staticmethod
    def fps_flat(x: int, y: int): ...
    @staticmethod
    def fps(position: Vector2): ...
    @staticmethod
    def clear_background_flat(r: int, g: int, b: int, a: int): ...
    @staticmethod
    def clear_background(color: Color): ...
