from typing import Any, Sequence, Tuple, Union, overload

class Vector4:
    x: float
    y: float
    z: float
    w: float

    @staticmethod
    def from_vector4(other: "Vector4") -> "Vector4": ...
    @staticmethod
    def from_list(other: list) -> "Vector4": ...
    @staticmethod
    def from_tuple(other: tuple) -> "Vector4": ...
    @staticmethod
    def from_ints(x: int, y: int, z: int, w: int) -> "Vector4": ...
    @staticmethod
    def from_floats(x: float, y: float, z: float, w: float) -> "Vector4": ...
    @staticmethod
    def from_xyzw(
        x: float | int, y: float | int, z: float | int, w: float | int
    ) -> "Vector4": ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, vector: "Vector4") -> None: ...
    @overload
    def __init__(self, sequence: Sequence[float]) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float, w: float) -> None: ...
    @property
    def xxxx(self) -> "Vector4": ...
    @property
    def xxxy(self) -> "Vector4": ...
    @property
    def xxxz(self) -> "Vector4": ...
    @property
    def xxxw(self) -> "Vector4": ...
    @property
    def xxyx(self) -> "Vector4": ...
    @property
    def xxyy(self) -> "Vector4": ...
    @property
    def xxyz(self) -> "Vector4": ...
    @property
    def xxyw(self) -> "Vector4": ...
    @property
    def xxzx(self) -> "Vector4": ...
    @property
    def xxzy(self) -> "Vector4": ...
    @property
    def xxzz(self) -> "Vector4": ...
    @property
    def xxzw(self) -> "Vector4": ...
    @property
    def xxwx(self) -> "Vector4": ...
    @property
    def xxwy(self) -> "Vector4": ...
    @property
    def xxwz(self) -> "Vector4": ...
    @property
    def xxww(self) -> "Vector4": ...
    @property
    def xyxx(self) -> "Vector4": ...
    @property
    def xyxy(self) -> "Vector4": ...
    @property
    def xyxz(self) -> "Vector4": ...
    @property
    def xyxw(self) -> "Vector4": ...
    @property
    def xyyx(self) -> "Vector4": ...
    @property
    def xyyy(self) -> "Vector4": ...
    @property
    def xyyz(self) -> "Vector4": ...
    @property
    def xyyw(self) -> "Vector4": ...
    @property
    def xyzx(self) -> "Vector4": ...
    @property
    def xyzy(self) -> "Vector4": ...
    @property
    def xyzz(self) -> "Vector4": ...
    @property
    def xyzw(self) -> "Vector4": ...
    @property
    def xywx(self) -> "Vector4": ...
    @property
    def xywy(self) -> "Vector4": ...
    @property
    def xywz(self) -> "Vector4": ...
    @property
    def xyww(self) -> "Vector4": ...
    @property
    def xzxx(self) -> "Vector4": ...
    @property
    def xzxy(self) -> "Vector4": ...
    @property
    def xzxz(self) -> "Vector4": ...
    @property
    def xzxw(self) -> "Vector4": ...
    @property
    def xzyx(self) -> "Vector4": ...
    @property
    def xzyy(self) -> "Vector4": ...
    @property
    def xzyz(self) -> "Vector4": ...
    @property
    def xzyw(self) -> "Vector4": ...
    @property
    def xzzx(self) -> "Vector4": ...
    @property
    def xzzy(self) -> "Vector4": ...
    @property
    def xzzz(self) -> "Vector4": ...
    @property
    def xzzw(self) -> "Vector4": ...
    @property
    def xzwx(self) -> "Vector4": ...
    @property
    def xzwy(self) -> "Vector4": ...
    @property
    def xzwz(self) -> "Vector4": ...
    @property
    def xzww(self) -> "Vector4": ...
    @property
    def xwxx(self) -> "Vector4": ...
    @property
    def xwxy(self) -> "Vector4": ...
    @property
    def xwxz(self) -> "Vector4": ...
    @property
    def xwxw(self) -> "Vector4": ...
    @property
    def xwyx(self) -> "Vector4": ...
    @property
    def xwyy(self) -> "Vector4": ...
    @property
    def xwyz(self) -> "Vector4": ...
    @property
    def xwyw(self) -> "Vector4": ...
    @property
    def xwzx(self) -> "Vector4": ...
    @property
    def xwzy(self) -> "Vector4": ...
    @property
    def xwzz(self) -> "Vector4": ...
    @property
    def xwzw(self) -> "Vector4": ...
    @property
    def xwwx(self) -> "Vector4": ...
    @property
    def xwwy(self) -> "Vector4": ...
    @property
    def xwwz(self) -> "Vector4": ...
    @property
    def xwww(self) -> "Vector4": ...
    @property
    def yxxx(self) -> "Vector4": ...
    @property
    def yxxy(self) -> "Vector4": ...
    @property
    def yxxz(self) -> "Vector4": ...
    @property
    def yxxw(self) -> "Vector4": ...
    @property
    def yxyx(self) -> "Vector4": ...
    @property
    def yxyy(self) -> "Vector4": ...
    @property
    def yxyz(self) -> "Vector4": ...
    @property
    def yxyw(self) -> "Vector4": ...
    @property
    def yxzx(self) -> "Vector4": ...
    @property
    def yxzy(self) -> "Vector4": ...
    @property
    def yxzz(self) -> "Vector4": ...
    @property
    def yxzw(self) -> "Vector4": ...
    @property
    def yxwx(self) -> "Vector4": ...
    @property
    def yxwy(self) -> "Vector4": ...
    @property
    def yxwz(self) -> "Vector4": ...
    @property
    def yxww(self) -> "Vector4": ...
    @property
    def yyxx(self) -> "Vector4": ...
    @property
    def yyxy(self) -> "Vector4": ...
    @property
    def yyxz(self) -> "Vector4": ...
    @property
    def yyxw(self) -> "Vector4": ...
    @property
    def yyyx(self) -> "Vector4": ...
    @property
    def yyyy(self) -> "Vector4": ...
    @property
    def yyyz(self) -> "Vector4": ...
    @property
    def yyyw(self) -> "Vector4": ...
    @property
    def yyzx(self) -> "Vector4": ...
    @property
    def yyzy(self) -> "Vector4": ...
    @property
    def yyzz(self) -> "Vector4": ...
    @property
    def yyzw(self) -> "Vector4": ...
    @property
    def yywx(self) -> "Vector4": ...
    @property
    def yywy(self) -> "Vector4": ...
    @property
    def yywz(self) -> "Vector4": ...
    @property
    def yyww(self) -> "Vector4": ...
    @property
    def yzxx(self) -> "Vector4": ...
    @property
    def yzxy(self) -> "Vector4": ...
    @property
    def yzxz(self) -> "Vector4": ...
    @property
    def yzxw(self) -> "Vector4": ...
    @property
    def yzyx(self) -> "Vector4": ...
    @property
    def yzyy(self) -> "Vector4": ...
    @property
    def yzyz(self) -> "Vector4": ...
    @property
    def yzyw(self) -> "Vector4": ...
    @property
    def yzzx(self) -> "Vector4": ...
    @property
    def yzzy(self) -> "Vector4": ...
    @property
    def yzzz(self) -> "Vector4": ...
    @property
    def yzzw(self) -> "Vector4": ...
    @property
    def yzwx(self) -> "Vector4": ...
    @property
    def yzwy(self) -> "Vector4": ...
    @property
    def yzwz(self) -> "Vector4": ...
    @property
    def yzww(self) -> "Vector4": ...
    @property
    def ywxx(self) -> "Vector4": ...
    @property
    def ywxy(self) -> "Vector4": ...
    @property
    def ywxz(self) -> "Vector4": ...
    @property
    def ywxw(self) -> "Vector4": ...
    @property
    def ywyx(self) -> "Vector4": ...
    @property
    def ywyy(self) -> "Vector4": ...
    @property
    def ywyz(self) -> "Vector4": ...
    @property
    def ywyw(self) -> "Vector4": ...
    @property
    def ywzx(self) -> "Vector4": ...
    @property
    def ywzy(self) -> "Vector4": ...
    @property
    def ywzz(self) -> "Vector4": ...
    @property
    def ywzw(self) -> "Vector4": ...
    @property
    def ywwx(self) -> "Vector4": ...
    @property
    def ywwy(self) -> "Vector4": ...
    @property
    def ywwz(self) -> "Vector4": ...
    @property
    def ywww(self) -> "Vector4": ...
    @property
    def zxxx(self) -> "Vector4": ...
    @property
    def zxxy(self) -> "Vector4": ...
    @property
    def zxxz(self) -> "Vector4": ...
    @property
    def zxxw(self) -> "Vector4": ...
    @property
    def zxyx(self) -> "Vector4": ...
    @property
    def zxyy(self) -> "Vector4": ...
    @property
    def zxyz(self) -> "Vector4": ...
    @property
    def zxyw(self) -> "Vector4": ...
    @property
    def zxzx(self) -> "Vector4": ...
    @property
    def zxzy(self) -> "Vector4": ...
    @property
    def zxzz(self) -> "Vector4": ...
    @property
    def zxzw(self) -> "Vector4": ...
    @property
    def zxwx(self) -> "Vector4": ...
    @property
    def zxwy(self) -> "Vector4": ...
    @property
    def zxwz(self) -> "Vector4": ...
    @property
    def zxww(self) -> "Vector4": ...
    @property
    def zyxx(self) -> "Vector4": ...
    @property
    def zyxy(self) -> "Vector4": ...
    @property
    def zyxz(self) -> "Vector4": ...
    @property
    def zyxw(self) -> "Vector4": ...
    @property
    def zyyx(self) -> "Vector4": ...
    @property
    def zyyy(self) -> "Vector4": ...
    @property
    def zyyz(self) -> "Vector4": ...
    @property
    def zyyw(self) -> "Vector4": ...
    @property
    def zyzx(self) -> "Vector4": ...
    @property
    def zyzy(self) -> "Vector4": ...
    @property
    def zyzz(self) -> "Vector4": ...
    @property
    def zyzw(self) -> "Vector4": ...
    @property
    def zywx(self) -> "Vector4": ...
    @property
    def zywy(self) -> "Vector4": ...
    @property
    def zywz(self) -> "Vector4": ...
    @property
    def zyww(self) -> "Vector4": ...
    @property
    def zzxx(self) -> "Vector4": ...
    @property
    def zzxy(self) -> "Vector4": ...
    @property
    def zzxz(self) -> "Vector4": ...
    @property
    def zzxw(self) -> "Vector4": ...
    @property
    def zzyx(self) -> "Vector4": ...
    @property
    def zzyy(self) -> "Vector4": ...
    @property
    def zzyz(self) -> "Vector4": ...
    @property
    def zzyw(self) -> "Vector4": ...
    @property
    def zzzx(self) -> "Vector4": ...
    @property
    def zzzy(self) -> "Vector4": ...
    @property
    def zzzz(self) -> "Vector4": ...
    @property
    def zzzw(self) -> "Vector4": ...
    @property
    def zzwx(self) -> "Vector4": ...
    @property
    def zzwy(self) -> "Vector4": ...
    @property
    def zzwz(self) -> "Vector4": ...
    @property
    def zzww(self) -> "Vector4": ...
    @property
    def zwxx(self) -> "Vector4": ...
    @property
    def zwxy(self) -> "Vector4": ...
    @property
    def zwxz(self) -> "Vector4": ...
    @property
    def zwxw(self) -> "Vector4": ...
    @property
    def zwyx(self) -> "Vector4": ...
    @property
    def zwyy(self) -> "Vector4": ...
    @property
    def zwyz(self) -> "Vector4": ...
    @property
    def zwyw(self) -> "Vector4": ...
    @property
    def zwzx(self) -> "Vector4": ...
    @property
    def zwzy(self) -> "Vector4": ...
    @property
    def zwzz(self) -> "Vector4": ...
    @property
    def zwzw(self) -> "Vector4": ...
    @property
    def zwwx(self) -> "Vector4": ...
    @property
    def zwwy(self) -> "Vector4": ...
    @property
    def zwwz(self) -> "Vector4": ...
    @property
    def zwww(self) -> "Vector4": ...
    @property
    def wxxx(self) -> "Vector4": ...
    @property
    def wxxy(self) -> "Vector4": ...
    @property
    def wxxz(self) -> "Vector4": ...
    @property
    def wxxw(self) -> "Vector4": ...
    @property
    def wxyx(self) -> "Vector4": ...
    @property
    def wxyy(self) -> "Vector4": ...
    @property
    def wxyz(self) -> "Vector4": ...
    @property
    def wxyw(self) -> "Vector4": ...
    @property
    def wxzx(self) -> "Vector4": ...
    @property
    def wxzy(self) -> "Vector4": ...
    @property
    def wxzz(self) -> "Vector4": ...
    @property
    def wxzw(self) -> "Vector4": ...
    @property
    def wxwx(self) -> "Vector4": ...
    @property
    def wxwy(self) -> "Vector4": ...
    @property
    def wxwz(self) -> "Vector4": ...
    @property
    def wxww(self) -> "Vector4": ...
    @property
    def wyxx(self) -> "Vector4": ...
    @property
    def wyxy(self) -> "Vector4": ...
    @property
    def wyxz(self) -> "Vector4": ...
    @property
    def wyxw(self) -> "Vector4": ...
    @property
    def wyyx(self) -> "Vector4": ...
    @property
    def wyyy(self) -> "Vector4": ...
    @property
    def wyyz(self) -> "Vector4": ...
    @property
    def wyyw(self) -> "Vector4": ...
    @property
    def wyzx(self) -> "Vector4": ...
    @property
    def wyzy(self) -> "Vector4": ...
    @property
    def wyzz(self) -> "Vector4": ...
    @property
    def wyzw(self) -> "Vector4": ...
    @property
    def wywx(self) -> "Vector4": ...
    @property
    def wywy(self) -> "Vector4": ...
    @property
    def wywz(self) -> "Vector4": ...
    @property
    def wyww(self) -> "Vector4": ...
    @property
    def wzxx(self) -> "Vector4": ...
    @property
    def wzxy(self) -> "Vector4": ...
    @property
    def wzxz(self) -> "Vector4": ...
    @property
    def wzxw(self) -> "Vector4": ...
    @property
    def wzyx(self) -> "Vector4": ...
    @property
    def wzyy(self) -> "Vector4": ...
    @property
    def wzyz(self) -> "Vector4": ...
    @property
    def wzyw(self) -> "Vector4": ...
    @property
    def wzzx(self) -> "Vector4": ...
    @property
    def wzzy(self) -> "Vector4": ...
    @property
    def wzzz(self) -> "Vector4": ...
    @property
    def wzzw(self) -> "Vector4": ...
    @property
    def wzwx(self) -> "Vector4": ...
    @property
    def wzwy(self) -> "Vector4": ...
    @property
    def wzwz(self) -> "Vector4": ...
    @property
    def wzww(self) -> "Vector4": ...
    @property
    def wwxx(self) -> "Vector4": ...
    @property
    def wwxy(self) -> "Vector4": ...
    @property
    def wwxz(self) -> "Vector4": ...
    @property
    def wwxw(self) -> "Vector4": ...
    @property
    def wwyx(self) -> "Vector4": ...
    @property
    def wwyy(self) -> "Vector4": ...
    @property
    def wwyz(self) -> "Vector4": ...
    @property
    def wwyw(self) -> "Vector4": ...
    @property
    def wwzx(self) -> "Vector4": ...
    @property
    def wwzy(self) -> "Vector4": ...
    @property
    def wwzz(self) -> "Vector4": ...
    @property
    def wwzw(self) -> "Vector4": ...
    @property
    def wwwx(self) -> "Vector4": ...
    @property
    def wwwy(self) -> "Vector4": ...
    @property
    def wwwz(self) -> "Vector4": ...
    @property
    def wwww(self) -> "Vector4": ...
    def get_tuple(self) -> Tuple[float, float, float, float]: ...
    def get_int_tuple(self) -> Tuple[int, int, int, int]: ...
    def get_rounded_tuple(self) -> Tuple[int, int, int, int]: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __add__(self, other: "Vector4") -> "Vector4": ...
    def __sub__(self, other: "Vector4") -> "Vector4": ...
    def __mul__(self, other: Union["Vector4", int, float]) -> "Vector4": ...
    def __truediv__(self, other: Union["Vector4", int, float]) -> "Vector4": ...
    def __floordiv__(self, other: Union["Vector4", int, float]) -> "Vector4": ...
    def __iadd__(self, other: "Vector4") -> "Vector4": ...
    def __isub__(self, other: "Vector4") -> "Vector4": ...
    def __imul__(self, other: "Vector4") -> "Vector4": ...
    def __neg__(self) -> "Vector4": ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
    def __copy__(self) -> "Vector4": ...
    def __deepcopy__(self, memo: Any) -> "Vector4": ...
    def copy(self) -> "Vector4": ...
    def to_round(self) -> "Vector4": ...
    def get_round(self) -> "Vector4": ...
    def to_abs(self) -> "Vector4": ...
    def get_abs(self) -> "Vector4": ...
    def to_neg(self) -> "Vector4": ...
    def get_neg(self) -> "Vector4": ...
    @property
    def length(self) -> float: ...
    def sadd(self, new_vec: "Vector4", old_vec: "Vector4") -> None: ...
    def to_normalized(self) -> "Vector4": ...
    def get_normalized(self) -> "Vector4": ...
    def distance_to(self, other: "Vector4") -> float: ...
    def distance_squared_to(self, other: "Vector4") -> float: ...
    def dot(self, other: "Vector4") -> float: ...
