from typing import Any, Sequence, Tuple, Union, overload

class Vector3:
    x: float
    y: float
    z: float

    @staticmethod
    def from_vector3(other: "Vector3") -> "Vector3": ...
    @staticmethod
    def from_list(other: list) -> "Vector3": ...
    @staticmethod
    def from_tuple(other: tuple) -> "Vector3": ...
    @staticmethod
    def from_ints(x: int, y: int, z: int) -> "Vector3": ...
    @staticmethod
    def from_floats(x: float, y: float, z: float) -> "Vector3": ...
    @staticmethod
    def from_xyz(x: float | int, y: float | int, z: float | int) -> "Vector3": ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, vector: "Vector3") -> None: ...
    @overload
    def __init__(self, sequence: Sequence[float]) -> None: ...
    @overload
    def __init__(self, x: float, y: float, z: float) -> None: ...
    @property
    def xxx(self) -> "Vector3": ...
    @property
    def xxy(self) -> "Vector3": ...
    @property
    def xxz(self) -> "Vector3": ...
    @property
    def xyx(self) -> "Vector3": ...
    @property
    def xyy(self) -> "Vector3": ...
    @property
    def xyz(self) -> "Vector3": ...
    @property
    def xzy(self) -> "Vector3": ...
    @property
    def xzx(self) -> "Vector3": ...
    @property
    def xzz(self) -> "Vector3": ...
    @property
    def yxx(self) -> "Vector3": ...
    @property
    def yxy(self) -> "Vector3": ...
    @property
    def yxz(self) -> "Vector3": ...
    @property
    def yyx(self) -> "Vector3": ...
    @property
    def yyy(self) -> "Vector3": ...
    @property
    def yyz(self) -> "Vector3": ...
    @property
    def yzx(self) -> "Vector3": ...
    @property
    def yzy(self) -> "Vector3": ...
    @property
    def yzz(self) -> "Vector3": ...
    @property
    def zxx(self) -> "Vector3": ...
    @property
    def zxy(self) -> "Vector3": ...
    @property
    def zxz(self) -> "Vector3": ...
    @property
    def zyx(self) -> "Vector3": ...
    @property
    def zyy(self) -> "Vector3": ...
    @property
    def zyz(self) -> "Vector3": ...
    @property
    def zzx(self) -> "Vector3": ...
    @property
    def zzy(self) -> "Vector3": ...
    @property
    def zzz(self) -> "Vector3": ...
    def get_tuple(self) -> Tuple[float, float, float]: ...
    def get_int_tuple(self) -> Tuple[int, int, int]: ...
    def get_rounded_tuple(self) -> Tuple[int, int, int]: ...
    def __getitem__(self, index: int) -> float: ...
    def __setitem__(self, index: int, value: float) -> None: ...
    def __add__(self, other: "Vector3") -> "Vector3": ...
    def __sub__(self, other: "Vector3") -> "Vector3": ...
    def __mul__(self, other: Union["Vector3", int, float]) -> "Vector3": ...
    def __truediv__(self, other: Union["Vector3", int, float]) -> "Vector3": ...
    def __floordiv__(self, other: Union["Vector3", int, float]) -> "Vector3": ...
    def __iadd__(self, other: "Vector3") -> "Vector3": ...
    def __isub__(self, other: "Vector3") -> "Vector3": ...
    def __imul__(self, other: "Vector3") -> "Vector3": ...
    def __neg__(self) -> "Vector3": ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: Any) -> bool: ...
    def __copy__(self) -> "Vector3": ...
    def __deepcopy__(self, memo: Any) -> "Vector3": ...
    def copy(self) -> "Vector3": ...
    def to_round(self) -> "Vector3": ...
    def get_round(self) -> "Vector3": ...
    def to_abs(self) -> "Vector3": ...
    def get_abs(self) -> "Vector3": ...
    def to_neg(self) -> "Vector3": ...
    def get_neg(self) -> "Vector3": ...
    @property
    def length(self) -> float: ...
    def sadd(self, new_vec: "Vector3", old_vec: "Vector3") -> None: ...
    def to_normalized(self) -> "Vector3": ...
    def get_normalized(self) -> "Vector3": ...
    def distance_to(self, other: "Vector3") -> float: ...
    def distance_squared_to(self, other: "Vector3") -> float: ...
    def dot(self, other: "Vector3") -> float: ...
    def cross(self, other: "Vector3") -> "Vector3": ...
