import json
from pathlib import Path

with open("raylib_api.json", "r") as f:
    api = json.load(f)

tab = "    "

result = """#AutoGenerated
cdef extern from "stdarg.h" nogil:
    ctypedef struct va_list:
        pass

cdef extern from "raylib.h" nogil:
    #=== PLACEHOLDERS ===
    struct rAudioBuffer:
        pass
    struct rAudioProcessor:
        pass"""

to_correct_type = {"bool": "bint"}


class BaseItem:
    def __init__(self, type: str, name: str, description: str = ""):
        self.type = type
        if self.type in to_correct_type:
            self.type = to_correct_type[self.type]
        self.name = name
        self.desc = description

    def __repr__(self) -> str:
        return f"ITEM: {self.name}, {self.desc}, {self.type}"

    def __str__(self) -> str:
        return f"{self.type} {self.name}" if self.type != "..." else f"{self.type}"


class Alias(BaseItem):
    def __str__(self) -> str:
        return tab + f"ctypedef {self.type} {self.name}"


class Struct:
    def __init__(self, name: str, description: str, fields: list):
        self.name = name
        self.desc = description
        self.fields = fields
        self.aliases = []
        for i in range(len(fields)):
            self.fields[i] = BaseItem(**self.fields[i])

    def __repr__(self) -> str:
        return f"STRUCT: {self.name} | {self.desc} | {self.fields}"

    def __str__(self) -> str:
        first_line = f"{tab}struct {self.name}:\n"
        other_lines = (tab * 2).join(
            [f"{field.type} {field.name}\n" for field in self.fields]
        )
        if self.aliases:
            alias_line = "\n" + "\n".join([str(alias) for alias in self.aliases]) + "\n"
        else:
            alias_line = ""
        return first_line + (tab * 2) + other_lines + alias_line


class Function:
    def __init__(self, name: str, description: str, returnType: str, params: list = []):
        self.name = name
        self.desc = description
        self.params = params
        self.return_type = returnType
        if params:
            for i in range(len(params)):
                self.params[i] = BaseItem(**self.params[i])

    def as_callback(self):
        return f"ctypedef {self.return_type}(*{self.name})({', '.join(str(param) for param in self.params)})"

    def __str__(self) -> str:
        comment_line = f"#Info: {self.desc}\n"
        command_line = f"{tab}{self.return_type} {self.name}({', '.join(str(param) for param in self.params)})"
        return comment_line + command_line


api_structs = api["structs"]
api_aliases = api["aliases"]
api_callbacks = api["callbacks"]
api_functions = api["functions"]

py_structs = [Struct(**item) for item in api_structs]
struct_names = [item.name for item in py_structs]

py_aliases = [Alias(**item) for item in api_aliases]
for alias in py_aliases:
    result_struct = next(struct for struct in py_structs if struct.name == alias.type)
    if result_struct:
        result_struct.aliases.append(alias)

py_callbacks = [Function(**item) for item in api_callbacks]
py_functions = [Function(**item) for item in api_functions]

# === Result ===
result += "\n" + tab + "# === Structs ==="
structs_code = "\n".join([str(struct) for struct in py_structs])
result += "\n" + structs_code + "\n"
callback_code = f"\n{tab}".join([flike.as_callback() for flike in py_callbacks])
result += "\n" + tab + "# === Callbacks ===\n"
result += f"\n{tab}" + callback_code + "\n"
functions_code = f"\n\n{tab}".join([str(flike) for flike in py_functions])
result += "\n" + tab + "# === Functions ===\n"
result += f"\n{tab}" + functions_code + "\n"

output_path = Path("src/cyrlib/raylib/raylib.pxd")
output_path.write_text(result, encoding="utf-8")
